### ISSUE TITLE
多轮对话设计器，编辑测试时，发送“你好”，报错

### ISSUE THREAD

**Issue by coderzcr** [chatopera/docs#100]
## 现在行为
多轮对话设计器，编辑测试时，发送“你好”，报错
![image](https://github.com/chatopera/docs/assets/37607051/feb23f15-be12-4aff-a578-c4fd295730d5)

## 操作系统
Windows 11

**Comment by hailiang-wang** [comment]
经测试未能重现，请提供更多信息：

1）机器人的语料有什么改动，在默认创建后做了什么调整？

2）帮忙截图，获得更多的日志信息，见下图滚动条滚动到最下。

<img width="664" alt="screenshot_20231009152750" src="https://github.com/chatopera/docs/assets/3538629/b006c399-6e09-4fc5-ab6c-52c2a92b6441">

**Comment by hailiang-wang** [comment]
3）使用调试控制台。

如下图，发送【你好】前，打开调试控制台，检查对话过程中，有无错误信息。

<img width="243" alt="screenshot_20231009153157" src="https://github.com/chatopera/docs/assets/3538629/f124d200-3a50-4e26-8386-a51b9e6b97bd">

以上。感谢。
