### ISSUE TITLE
意图识别，将匹配的属性搞反了？前天还正常，今天发现匹配混了，是否bug？ 

### ISSUE THREAD

**Issue by diaohongyong** [chatopera/docs#102]
## 现在行为
意图识别：将匹配的属性搞反了？前天还正常，今天发现匹配混了，是否bug？ 

见下图，意图识别开始 -> 提示输入手机号后4位 -> 输入之后，意图识别却将输入的内容匹配到  "订单号"属性上了； 之后，仍然提示输入手机号 。

<img width="843" alt="Screenshot at 10月 26 00-41-38" src="https://github.com/chatopera/docs/assets/63226907/7c97b41f-f059-4d17-9ce0-493e07ebae92">
<img width="880" alt="Screenshot at 10月 26 00-45-05" src="https://github.com/chatopera/docs/assets/63226907/4abea410-4b48-4e96-a3d5-05e3fb89ca7c">

**Comment by hailiang-wang** [comment]
看起来是 BUG，今天开始修复，预计本周五之内可以升级。
感谢您的反馈。

**Comment by hailiang-wang** [comment]
@diaohongyong 

这个 BUG 修正了，线上更新了。
请您验证一下吧，如果问题解决，关闭工单即可。
感谢。

---

目前对话测试后

![screenshot_20231026113927](https://github.com/chatopera/docs/assets/3538629/dc2ac282-2210-4a9a-9806-ed6d80edca91)
