### ISSUE TITLE
无法打开凭证购买链接

### ISSUE THREAD

**Issue by somewhere1** [chatopera/docs#105]
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

**Comment by hailiang-wang** [comment]
最快下午，最晚明天下午恢复。
机房改造，非常抱歉。

Cheers.
Hai Liang W.
________________________________
From: ***@***.*** ***@***.***> on behalf of somewhere1 ***@***.***>
Sent: Sunday, February 25, 2024 11:51:32 AM
To: chatopera/docs ***@***.***>
Cc: Hai Liang W. ***@***.***>; Assign ***@***.***>
Subject: [chatopera/docs] 无法打开凭证购买链接 (Issue #105)


描述
功能
操作系统

  *    macOS or Mac OSX
  *    Windows
  *    Linux(Debian, CentOS, Ubuntu, etc.)

―

**Comment by hailiang-wang** [comment]
服务现在恢复了，您可以使用证书商店了。
感谢您的耐心等待。

Cheers.
Hai Liang W.
________________________________
