### ISSUE TITLE
运行SDK显示一直在训练

### ISSUE THREAD

**Issue by zhyhuayong** [chatopera/docs#20]
我按照gitee上的步骤用docker安装了服务，然后下载SDK运行，显示一直在训练
![image](https://user-images.githubusercontent.com/23372028/103185397-3815b200-48f7-11eb-8541-63c421ace9df.png)
表结构是这样的，是不是什么表缺失了？
![image](https://user-images.githubusercontent.com/23372028/103185411-4c59af00-48f7-11eb-9c06-ecd0fa630fe9.png)

**Comment by hailiang-wang** [comment]
clause  目前停止维护了，现在请使用 Chatopera 云服务，https://bot.chatopera.com
