### ISSUE TITLE
开发环境使用官网云机器人无法识别出意图并且没有正确回复

### ISSUE THREAD

**Issue by really** [chatopera/docs#21]
# 描述
您好，我在贵公司的官网云服务平台添加了测试的【点外卖】范例意图，并且已经更新发布了。在官网测试是好的，为什么在本地环境测试的时候，无法智能回复呢？是哪里还没有配置好么？

![微信图片_20210115110646](https://user-images.githubusercontent.com/21981/104676227-f0c65880-5721-11eb-8fe7-5707f1402cc2.png)
![微信图片_20210115110651](https://user-images.githubusercontent.com/21981/104676246-f7ed6680-5721-11eb-83ee-0e43a7eedc27.png)
![微信图片_20210115110656](https://user-images.githubusercontent.com/21981/104676260-fde34780-5721-11eb-97e6-cf76da26f2af.png)

## 功能
意图使用问题

# 环境

## 操作系统
-Windows 10

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by mukaiu** [comment]
春松客服机器人插件默认使用的是多轮对话。使用意图识别需调整机器人代码，写入业务规则。

**Comment by Samurais** [comment]
> 春松客服机器人插件默认使用的是多轮对话。使用意图识别需调整机器人代码，写入业务规则。

补充该回答。


1）春松客服里机器人客服插件只使用了多轮对话和知识库，没有使用意图识别。
2）意图识别使用前，需要在控制台发布测试通过的版本为**生产版本**，这个在意图识别的页面有。

![image](https://user-images.githubusercontent.com/3538629/104677110-cd041200-5723-11eb-965d-2da1a2836002.png)

3) 使用 SDK 在系统中集成意图识别，参考示例，https://github.com/chatopera/webchat 
核心参考代码：https://github.com/chatopera/webchat/blob/master/app/app.js

**Comment by really** [comment]
好的，大概了解了。谢谢您，我再研究下意图sdk方面的文档。 @Samurais @mukaiu

**Comment by hailiang-wang** [comment]
该服务已经通过意图匹配器实现。
https://docs.chatopera.com/products/chatbot-platform/howto-guides/convs/conv-gambit-intent.html
