### ISSUE TITLE
java sdk集成的功能范围

### ISSUE THREAD

**Issue by Luckyangle** [chatopera/docs#25]
我想问一下系统集成相关的问题，ChatBot类提供的api是否支持chatOpera云平台词典、知识库、意图和多轮会话知识输入模块的所有接口，以及问答检索的所有接口，文档中的API实例只包含了其中的一部分。

**Comment by hailiang-wang** [comment]
Java SDK 和 Nodejs SDK 的接口定义是一致的，都是通过 `command` API 来调用管理。
在 Chatopera CLI 中，这些接口更多，参考：

https://github.com/chatopera/chatopera-nodejs-sdk/tree/master/bin
