### ISSUE TITLE
春松客服，机器人进行多轮对话，点击产品列表无法发送text文本

### ISSUE THREAD

**Issue by zjfzwx** [chatopera/docs#29]
脚本文件:
//获得产品列表
+ 产品列表
- ^getProducts()
函数:
exports.getProducts = async function() {
    return {
        text: "我们有以下产品",
        params: [{
                label: "1.苹果",
                type: "qlist",
                text: "苹果的种类"
            },
            {
                label: "2.猕猴桃",
                type: "qlist",
                text: "猕猴桃的种类"
            }
        ]
    }
}
在春松客服，用户聊天界面无法发送用户点击的产品列表信息

**Comment by hailiang-wang** [comment]
春松客服访客和机器人对话的聊天控件是什么样子？
请截图。

**Comment by zjfzwx** [comment]
> 春松客服访客和机器人对话的聊天控件是什么样子？
> 请截图。

![Uploading QQ截图20210511104632.png…]()

**Comment by zjfzwx** [comment]
> 所以，点击“1.苹果”没有发送 “苹果的种类” 文本以及获得知识库回复？
> 整个界面没有变化？

是的，在春松客服里面点击无回复。但是对于指定问题的知识库回答又是有回复的。

**Comment by hailiang-wang** [comment]
bug fixed
