### ISSUE TITLE
在使用chatopera的时候无法获取内容

### ISSUE THREAD

**Issue by RelaxYeah** [chatopera/docs#30]
在JS①中引入了SDK并且绑定了机器人之后，在另一个JS，JS②中导入JS①。

但是由于机器人的消息都是 Promise { <pending> } 类型的，所以没有办法获取到想要的回复内容。

因为使用then会导致程序无法进行下去，所以想问问有没有什么办法可以直接不用.then获取到文本内容

**Comment by hailiang-wang** [comment]
可以使用 await async 来得到 then 的内容。

**Comment by hailiang-wang** [comment]
Promise 是一种编程规范，没有支持 promise 的接口可以封装为 promise。
参考 https://www.npmjs.com/package/q

这样的实现很多，所以：
`因为使用then会导致程序无法进行下去` 这个理论不成立。
