### ISSUE TITLE
能开发意图管理和多轮对话管理的接口吗？

### ISSUE THREAD

**Issue by viaco2ove** [chatopera/docs#31]
Chatopera 云服务
意图和多轮对话的增删查改接口好像没找到啊。是没开放吗？

**Comment by hailiang-wang** [comment]
意图识别增删改查 -- 没有在文档中提供，该接口逻辑比较复杂。
多轮对话增删改查 -- 参考 SDK，直接 deploy c66 文件，c66 文件中有脚本，话题。
https://www.npmjs.com/package/@chatopera/sdk

**Comment by hailiang-wang** [comment]
目前，在 CLI 中，已经支持意图的增删改查，接口使用参考：

https://docs.chatopera.com/products/chatbot-platform/integration/cli.html

CLI 的开源代码：

https://github.com/chatopera/chatopera-nodejs-sdk

和意图识别相关：

https://github.com/chatopera/chatopera-nodejs-sdk/blob/master/bin/intents.js
