### ISSUE TITLE
多轮对话设计器添加聊天机器人失败

### ISSUE THREAD

**Issue by huminghan** [chatopera/docs#39]
## 描述

多轮对话设计器添加聊天机器人失败，clientID、secret的信息都是直接复制的设置里面写信息，提示“信息不匹配请确认机器人信息”
![9b28d06d1544dac37dd8f29c39a7b9f](https://user-images.githubusercontent.com/73866913/133353121-d9f658e7-266d-49da-bb63-e53f3aed9821.png)

## 操作系统

 Windows

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
Please check out this guide

[可能遇到的问题](https://docs.chatopera.com/products/chatbot-platform/tutorials/1-create-bot.html#%E4%BF%A1%E6%81%AF%E4%B8%8D%E5%8C%B9%E9%85%8D%E8%AF%B7%E7%A1%AE%E8%AE%A4%E6%9C%BA%E5%99%A8%E4%BA%BA%E4%BF%A1%E6%81%AF
)

**Comment by hailiang-wang** [comment]
Suggest to follow this guide to build a simple bot to get familiar with Chatopera.

https://docs.chatopera.com/products/chatbot-platform/tutorials/index.html

We just refine the Docs, hope it helps and serve you better now, would like to hear from you.

**Comment by huminghan** [comment]
已成功，谢谢
