### ISSUE TITLE
意图识别设置之后不起作用

### ISSUE THREAD

**Issue by rxxy** [chatopera/docs#53]
## 现在行为
如图
![image](https://user-images.githubusercontent.com/14834156/144740614-fb5d460e-9819-4cfb-9f00-a1b3ca8eabfc.png)
![image](https://user-images.githubusercontent.com/14834156/144740634-6014bd38-71fb-4eb4-9d5a-567a9a00eac4.png)

![image](https://user-images.githubusercontent.com/14834156/144740640-60cbe5b5-50d8-4a71-aeb0-cdb880740b49.png)

## 操作系统

- [ ] macOS or Mac OSX
- [x] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 关于春松客服

- 春松客服：做好开源客服系统

[https://dwz.chatopera.com/7VLF0B](https://dwz.chatopera.com/7VLF0B)

- 《春松客服大讲堂》：面向开发者的免费视频教程来了

[https://dwz.chatopera.com/19K4R](https://dwz.chatopera.com/19K4R)

## Open Source for the World by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/144734473-df8ec8dd-ad0b-400f-8542-e4d40fb96375.jpg
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
首先，解决方案：
槽位 d 的词典使用系统词典：@ANY 来解析 ANY STRING.

至于为什么正则表达式没有生效：正则表达式设定的槽位，只在追问环节有作用，提取信息。在意图识别阶段，是分类问题，目前 Chatopera 机器人平台不支持正则表达式词典的槽位。这个问题在文档中，我们还没有添加，这个问题并不是 BUG。目前设计如此。

您现在完成 Chatopera 机器人平台入门教程了吗？

https://docs.chatopera.com/products/chatbot-platform/tutorials/index.html

**Comment by rxxy** [comment]
槽位 d 的词典使用系统词典：@ANY 来解析 ANY STRING.

我之前使用了系统词典@ANY来解析，也是一样的效果，所以我才建了自定义词典。

![image](https://user-images.githubusercontent.com/14834156/144772382-4e7fbc39-84b8-4446-bde4-be7cfbb6e2d1.png)
![image](https://user-images.githubusercontent.com/14834156/144772395-c655e8fc-a1cf-4f81-b49e-6f89e1d8cc9e.png)

**Comment by hailiang-wang** [comment]
Sorry，我上一段描述有误，这里，@ANY 的槽位，用在说法中，也是没有效果的。
需要尽量的补充说法；现在设计的考虑是，说法要尽量和用户的输入匹配。
@ANY 或 正则的话，不能作为一个有效的训练数据。

同时，这里在产品上确实有优化的空间。

**Comment by hailiang-wang** [comment]
意图识别模块中，说法更需要准确描述，使用的槽位的词典，绑定了词汇表，也是会做笛卡尔积，增强数据。
在您举的例子中，其实可以通过多轮对话脚本的模糊匹配器来实现，然后从模糊匹配器再跳转到意图识别匹配器。

从模糊匹配器，到意图匹配器的跳转：

假如多轮对话脚本的技能是：`intents`。

![image](https://user-images.githubusercontent.com/3538629/144774793-cd163322-a4fb-403f-bc5d-322e1e5e1fba.png)



```
// 意图匹配器
intent book_airplane_ticket
- ^succ()
- {x} ^lose()

// 从模糊匹配器跳转
+ ${0.5}{自定义的文本}
- ^topicRedirect("intents", "book_airplane_ticket", true)

```


详细参考：


- [模糊匹配器](https://docs.chatopera.com/products/chatbot-platform/howto-guides/conv-gambit-like.html)
- [意图匹配器](https://docs.chatopera.com/products/chatbot-platform/howto-guides/conv-gambit-intent.html)

**Comment by rxxy** [comment]
好的，谢谢，我再试试

**Comment by hailiang-wang** [comment]
感谢提交反馈，Chatopera 机器人平台的每个对话技能实现模块，都有优势和劣势，所以，我们的多轮对话解决方案是融合了规则，搜索和机器学习的。在不同对话任务中，使用不同的模块，最后通过多轮对话设计器来整合。

您通过入门教程可以轻松的了解多轮对话设计器的使用：

https://docs.chatopera.com/products/chatbot-platform/tutorials/index.html
