### ISSUE TITLE
如何将训练后的模型集成到离线模式中？

### ISSUE THREAD

**Issue by mrxf** [chatopera/docs#58]
## 描述
在集成的SDK中看到，都是使用http的方式请求对应的api服务器。请问如果需要**离线使用**比如单机模式情况，有可行方案吗？

## 功能
离线使用训练后的模型。

## 操作系统

- [x] Android and iOS
- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## Open Source for the World

[![banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/159913838-fbed2a14-a735-45b3-9e48-4727780a0d96.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
如果需要离线使用，那么就只有一个模式：Chatopera 云服务的私有部署，https://docs.chatopera.com/products/chatbot-platform/contract/on-premise.html

意图识别功能包含在加强版和全家桶中。

如需要采购，欢迎垂询：

[https://oh-my.cskefu.com/im/text/1frusw.html](https://oh-my.cskefu.com/im/text/1frusw.html)
