### ISSUE TITLE
在知识库中下载热门问题，其中包含了已经被删除的问题

### ISSUE THREAD

**Issue by halfray** [chatopera/docs#62]

**Comment by hailiang-wang** [comment]
本周内完成修复，会在本 issue 更新状态。
感谢反馈。

**Comment by hailiang-wang** [comment]
该问题已经解决。在您验证后，点击关闭【close with comment】, 感谢！

![screenshot_20230316122544](https://user-images.githubusercontent.com/3538629/225514255-4a41cc93-98da-46e4-898d-c32e8681afdf.png)

**Comment by halfray** [comment]
问题依然存在， 我的机器人clientId 是 63db4aeaac2af00013031462 ，目前知识库中只有3个问题，但是导出热门问题还有10条

**Comment by hailiang-wang** [comment]
完成升级了，现在问题解决了。
感谢，帮忙验证一下。

**Comment by halfray** [comment]
OK 问题已解决
