### ISSUE TITLE
知识库导出热门问题报错

### ISSUE THREAD

**Issue by halfray** [chatopera/docs#63]
在知识库中下载热门问题时，提示导出失败
通过java sdk 查询热门问题是也报错

日志:
DEBUG org.apache.http.wire - http-outgoing-6 >> "GET /api/v1/chatbot/63db4aeaac2af00013031462/faq/database/inquiryrank?sdklang=java HTTP/1.1[\r][\n]"
15:20:06.490 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 >> "Authorization: eyJyYW5kb20iOiI2ODA0NzY4OTk1Iiwic2lnbmF0dXJlIjoiNzk2MDZkYmVkMGY0ZDMzMGM1YTA0OGE0MTI3NGFiM2ExNWFkNDA5NCIsImFwcElkIjoiNjNkYjRhZWFhYzJhZjAwMDEzMDMxNDYyIiwidGltZXN0YW1wIjoiMTY3ODg2NDgwNiJ9[\r][\n]"
15:20:06.490 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 >> "Accept: application/json[\r][\n]"
15:20:06.490 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 >> "Content-Type: application/json[\r][\n]"
15:20:06.490 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 >> "user-agent: unirest-java/3.1.00[\r][\n]"
15:20:06.490 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 >> "accept-encoding: gzip[\r][\n]"
15:20:06.490 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 >> "Host: bot.chatopera.com[\r][\n]"
15:20:06.490 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 >> "Connection: Keep-Alive[\r][\n]"
15:20:06.490 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 >> "[\r][\n]"
15:20:06.540 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
15:20:06.540 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 << "Content-Length: 21[\r][\n]"
15:20:06.540 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 << "Content-Type: text/plain; charset=utf-8[\r][\n]"
15:20:06.540 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 << "Date: Wed, 15 Mar 2023 07:20:06 GMT[\r][\n]"
15:20:06.540 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 << "Server: Caddy[\r][\n]"
15:20:06.540 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 << "X-Powered-By: Express[\r][\n]"
15:20:06.540 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 << "[\r][\n]"
15:20:06.540 [http-nio-8083-exec-8] DEBUG org.apache.http.wire - http-outgoing-6 << "Internal Server Error"
15:20:06.540 [http-nio-8083-exec-8] DEBUG org.apache.http.headers - http-outgoing-6 << HTTP/1.1 500 Internal Server Error
15:20:06.540 [http-nio-8083-exec-8] DEBUG org.apache.http.headers - http-outgoing-6 << Content-Length: 21
15:20:06.540 [http-nio-8083-exec-8] DEBUG org.apache.http.headers - http-outgoing-6 << Content-Type: text/plain; charset=utf-8
15:20:06.540 [http-nio-8083-exec-8] DEBUG org.apache.http.headers - http-outgoing-6 << Date: Wed, 15 Mar 2023 07:20:06 GMT
15:20:06.540 [http-nio-8083-exec-8] DEBUG org.apache.http.headers - http-outgoing-6 << Server: Caddy
15:20:06.540 [http-nio-8083-exec-8] DEBUG org.apache.http.headers - http-outgoing-6 << X-Powered-By: Express
15:20:06.540 [http-nio-8083-exec-8] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection can be kept alive indefinitely

**Comment by hailiang-wang** [comment]
预计本周解决，和 #62 一起更新上线。
感谢反馈。

**Comment by hailiang-wang** [comment]
该问题的原因和 #62 相同的，在验证 #62 通过后，该问题也解决了。

**Comment by halfray** [comment]
该问题已解决，但是 #62 问题依然存在
