### ISSUE TITLE
知识库匹配的结果与预期不一致，匹配的逻辑是什么，有没有权重词的管理

### ISSUE THREAD

**Issue by halfray** [chatopera/docs#65]
提问的问题： 东南亚航线有优惠吗

返回的结果：
你是不是想问以下问题？

1. 如何查看是否有拼团价格？
2. 如何线上对账？
3. 如何在平台上完成订舱？
4. 目前平台上有哪些服务产品？
5. 如何获取并使用优惠券？
6. 优惠券有哪些使用规则？
7. 平台上会有哪些优惠活动？

为什么关于优惠的词并没有优先匹配第5,6,7项，而完全无关的1,2,3却排在前面。

在我们系统中类似优惠这种词的权重比较高，想要优先匹配，请问有没有权重词维护的相关功能，或者有没有办法让其优先匹配。

我系统机器人client Id 为 641801eab1fcf4001379a113

**Comment by hailiang-wang** [comment]
明天给您反馈。

**Comment by hailiang-wang** [comment]
这个问答可以修复，如果知识库里的检索不符合预期，那么可以使用多轮对话设计器解决。

## 和机器人集成的接口


首先，和 Chatopera BOT 云服务集成的接口，应使用多轮对话检索：

https://docs.chatopera.com/products/chatbot-platform/references/sdk/chatbot/chat.html

```
Chatbot#command("POST", "/conversation/query", body)
```

SDK 获得：[https://docs.chatopera.com/products/chatbot-platform/references/sdk/index.html](https://docs.chatopera.com/products/chatbot-platform/references/sdk/index.html)

因为多轮对话检索的接口是融合多个模型的，知识库是其中的一个。
并且，在检索顺序上，知识库在意图识别和多轮对话脚本之后。

该接口的参数和返回值参考[文档链接](https://docs.chatopera.com/products/chatbot-platform/references/sdk/chatbot/chat.html#%E6%A3%80%E7%B4%A2%E5%A4%9A%E8%BD%AE%E5%AF%B9%E8%AF%9D)。

![screenshot_20230413103618](https://user-images.githubusercontent.com/3538629/231633366-b2b4bff7-d9fa-4cc5-925b-1df046c6a248.png)

在这个接口的返回值中，也包含了知识库，见返回值 `data.faq` 字段，但是系统的最佳回复，是 `data.string`。


## 关于”优惠券“的 case

基于您描述的问答对情况，我做了一个测试。

* 新建机器人

* 新建问答对

![screenshot_20230413103938](https://user-images.githubusercontent.com/3538629/231633772-f03abd73-af26-4612-aa41-d33971429e79.png)


* 测试知识库

![screenshot_20230413103901](https://user-images.githubusercontent.com/3538629/231633693-067dc73d-44ad-44d2-819b-94d5f41533e4.png)

排序确实不够理想，但是和您发的不一样，就是【优惠券】可以拍在第二位。

机器人的知识库检索是经过机器学习用数学概率判断的，不是通过关键词匹配，所以出现不及预期的排序结果。这个概率判断的出发点是可以尽可能的关联和问题有关的知识库，底层的模型需要不断的完善。

对于这些不及预期的，快速的修复的方案是在多轮对话脚本中，使用【匹配器】。


## 使用多轮对话修正 bad case

* 下载安装多轮对话设计器

![screenshot_20230413104329](https://user-images.githubusercontent.com/3538629/231634433-598b0fa3-88a0-4803-b0a6-c618c7a38754.png)

* 打开多轮对话设计器并导入机器人

![screenshot_20230413104428](https://user-images.githubusercontent.com/3538629/231634602-94deed01-6c80-4d0c-a85d-5c850ccf30d4.png)

* 打开新导入的机器人并创建话题，比如 【hotfix】

![screenshot_20230413104452](https://user-images.githubusercontent.com/3538629/231634731-1168fd58-3acd-4f21-a851-837e869c39c7.png)


* 编辑脚本 

```
+ (*) 优惠券 (*)
- 优惠券的介绍
```

保存并测试。

![screenshot_20230413104642](https://user-images.githubusercontent.com/3538629/231634971-a5d339a1-c6f0-49c0-91e4-9dd510d9a39c.png)


其中，`(*) 优惠券 (*)` 是一个[通配符匹配器](https://docs.chatopera.com/products/chatbot-platform/references/gambit-star.html)，此外还有：
* 模糊匹配器: https://docs.chatopera.com/products/chatbot-platform/howto-guides/conv-gambit-like.html
* 意图识别匹配器: https://docs.chatopera.com/products/chatbot-platform/howto-guides/conv-gambit-intent.html

比如，使用模糊匹配器，

```
+ ${0.5}{优惠券}
- 优惠券的介绍
```


在使用模糊匹配器时，可以查看到计算的排序详情：

![screenshot_20230413105101](https://user-images.githubusercontent.com/3538629/231635663-f38ce918-2fa5-4fc6-b0da-0882d31f80e1.png)

![screenshot_20230413105003](https://user-images.githubusercontent.com/3538629/231635526-49c6d537-e695-4a03-bf0c-72ad9ef1691f.png)

以上调试信息说明：

`帮我找优惠券` 与 `优惠券` 的相似度是 `0.47416`。

那么可以修正模糊匹配器

```
+ ${0.47}{优惠券}
- 优惠券的介绍
```

![screenshot_20230413105212](https://user-images.githubusercontent.com/3538629/231635848-86b2f8eb-fb45-41ae-aa96-7172501ded3e.png)

**Comment by hailiang-wang** [comment]
## 实现原理的补充说明

* 多轮对话的检索顺序：https://docs.chatopera.com/products/chatbot-platform/explanations/query.html
* 在春松客服中，使用 Java 请求多轮对话接口和返回值处理逻辑，https://github.com/cskefu/cskefu/blob/master/contact-center/app/src/main/java/com/cskefu/cc/plugins/chatbot/ChatbotEventSubscription.java#L121
* 在春松客服中，对返回值的展示：支持卡片消息等，https://docs.cskefu.com/docs/work-chatbot/message-types

**Comment by hailiang-wang** [comment]
## 使用匹配器时的状态

在多轮对话脚本中，匹配器是有记忆状态的，参考下面：

[https://docs.chatopera.com/products/chatbot-platform/howto-guides/conv-state.html](https://docs.chatopera.com/products/chatbot-platform/howto-guides/conv-state.html)

简单的说，如果一个问答在多轮对话脚本中，希望是一直对访问用户有效，那么需要使用 `{keep}`，比如：


```
+ {keep} (*) 优惠券 (*)
- 优惠券的介绍
```

**Comment by halfray** [comment]
我想知道是如何对没有达到阈值的排序结果进行干预，比如添加权重词： 如果问题中包含该权重词，则预设的知识库中包含该权重词的结果就优先展示。目前看是不提供这种方案的；

而如果采用多轮对话脚本的方式，我需要编写的脚本如下：
```
+ {keep} (*) 优惠 (*)
- {keep} ^faq_list()

exports.faq_list = async function() {
    return {
        text: "你是不是想问以下问题",
        params: [{
                label: "1. 平台上会有哪些优惠活动",
                type: "qlist",
                text: "平台上会有哪些优惠活动"
            },
            {
                label: "2.如何获取并使用优惠券",
                type: "qlist",
                text: "如何获取并使用优惠券"
            },
            {
                label: "3. 优惠券有哪些使用规则",
                type: "qlist",
                text: "优惠券有哪些使用规则"
            }
        ]
    };
}
```

这种方式岂不是将知识库的信息又重新维护了一遍吗？

**Comment by hailiang-wang** [comment]
您说的很有道理，设计的初衷是保证灵活性，而不是重复劳动。
这个合理的方案，应该是：
1）通过多轮对话改写查询，即在脚本回复（`-` 后面），提供一个函数，比如 `faqQueryRewrite("新的查询")` 

```
+ {keep} (*) 优惠 (*)
- ^faqQueryRewrite("平台上会有哪些优惠活动")
```

2）`faqQueryRewrite` 作为内置函数库，查询该机器人的知识库，并将结果返回

https://docs.chatopera.com/products/chatbot-platform/references/func-builtin/index.html

**Comment by hailiang-wang** [comment]
> 您说的很有道理，设计的初衷是保证灵活性，而不是重复劳动。 这个合理的方案，应该是： 1）通过多轮对话改写查询，即在脚本回复（`-` 后面），提供一个函数，比如 `faqQueryRewrite("新的查询")`
> 
> ```
> + {keep} (*) 优惠 (*)
> - ^faqQueryRewrite("平台上会有哪些优惠活动")
> ```
> 
> 2）`faqQueryRewrite` 作为内置函数库，查询该机器人的知识库，并将结果返回
> 
> https://docs.chatopera.com/products/chatbot-platform/references/func-builtin/index.html

您觉得这个方案可以吗？

**Comment by halfray** [comment]
"机器人的知识库检索是经过机器学习用数学概率判断的" 对于这句话我想问一下，如果用户问了一个问题，没有在知识库中命中，列出了相关问题给用户，用户自己选择了对应的相关问题。那这个相关问题会反馈给机器学习，用了增加这两个问题的匹配度吗 ，当用户再问出相同或相似问题时，用户选择过的推荐问题的得分会有所提高吗？

**Comment by hailiang-wang** [comment]
> "机器人的知识库检索是经过机器学习用数学概率判断的" 对于这句话我想问一下，如果用户问了一个问题，没有在知识库中命中，列出了相关问题给用户，用户自己选择了对应的相关问题。那这个相关问题会反馈给机器学习，用了增加这两个问题的匹配度吗 ，当用户再问出相同或相似问题时，用户选择过的推荐问题的得分会有所提高吗？

## 对话历史

现在反馈数据没有自动的直接优化到知识库，现在 Chatopera 机器人平台提供聚类分析，来对历史数据进行优化，但是需要在聚类之后人工处理，添加知识库。

![screenshot_20230414085535](https://user-images.githubusercontent.com/3538629/231914028-ad165e94-6cd8-413c-9acf-579abd53153d.png)

## 关于知识库检索的优化

昨天提到在多轮对话脚本里，提供和知识库集成的内置函数，下周会实现。


但是另外，我们从今天开始优化知识库检索，像上面的【优惠券】的例子，一定让有优惠券出现在上面。
这个优化直接优化知识库检索的模型，或许也会用上【词典】管理。

![screenshot_20230414085856](https://user-images.githubusercontent.com/3538629/231914283-aaea16ef-6974-4ed7-8b15-5a6725b4db2b.png)



## 词典管理

目前，知识库是支持词典管理的，只是没有作为关键词作为提升权重。

比如知识库有【优惠券介绍】，如果词典中有近义词：【优惠券,优惠码】，那么访客问【优惠码介绍】，这时【优惠券介绍】也出现。

**Comment by hailiang-wang** [comment]
知识库检索的优化，预计下周内可以完成。

**Comment by halfray** [comment]
期待优化后的结果，请在优化完成后给予回复，如果采用了词典作为关键词，请给与使用说明，非常感谢。

**Comment by hailiang-wang** [comment]
这个正在优化，并根据您的实际例子来完善。
在没有改变现在产品前，测试效果如下：

## 知识库

知识库导出文件：
[知识库 (2).zip](https://github.com/chatopera/docs/files/11247417/2.zip)


![screenshot_20230417152840](https://user-images.githubusercontent.com/3538629/232414995-6006f236-5634-4e92-8ac2-e1f48d0ffbca.png)


## 测试对话

其结果是符合预期的，即【优惠券】的问答对靠上。

![screenshot_20230417152819](https://user-images.githubusercontent.com/3538629/232414920-ff8ce78e-ba56-4bfc-88bf-534bbf417475.png)

## 您帮忙再验证一下 

您帮忙：

1）新建一个聊天机器人
2）导入知识库：知识库 (2).json 【见上 知识库 (2).zip 解压 】
3）进入对话测试，发送 “东南亚航线有优惠吗”，并得到结果。

您看是不是有关键词【优惠券】的问答对的分数比较高。

![screenshot_20230417153238](https://user-images.githubusercontent.com/3538629/232415853-f1125aed-e0e7-4a77-8efa-99c3694260ed.png)

对于您之前提到的这个返回结果：

提问的问题： 东南亚航线有优惠吗

```
你是不是想问以下问题？ -->

如何查看是否有拼团价格？
如何线上对账？
如何在平台上完成订舱？
目前平台上有哪些服务产品？
如何获取并使用优惠券？
优惠券有哪些使用规则？
平台上会有哪些优惠活动？
```

看上去是展示时，根据返回结果的 score 排序颠倒了。就是分数高的没有排到上面。
您的返回结果是怎么展示的。在 [对话检索](https://docs.chatopera.com/products/chatbot-platform/references/sdk/chatbot/chat.html) 接口中，都有 score 分数。

如下：

```
{
"id": "qo0PjocBgDTE2MpZ6San",
"score": 0.42601,
"post": "平台上会有哪些优惠活动？",
"replies": [
{
"rtype": "plain",
"enabled": true,
"content": "平台上会有哪些优惠活动？"
}
],
```

结果的相关性是 score 越高，越和问题相似。

**Comment by hailiang-wang** [comment]
> 这个正在优化，并根据您的实际例子来完善。 在没有改变现在产品前，测试效果如下：
> 
> ## 知识库
> 知识库导出文件： [知识库 (2).zip](https://github.com/chatopera/docs/files/11247417/2.zip)
> 
> ![screenshot_20230417152840](https://user-images.githubusercontent.com/3538629/232414995-6006f236-5634-4e92-8ac2-e1f48d0ffbca.png)
> 
> ## 测试对话
> 其结果是符合预期的，即【优惠券】的问答对靠上。
> 
> ![screenshot_20230417152819](https://user-images.githubusercontent.com/3538629/232414920-ff8ce78e-ba56-4bfc-88bf-534bbf417475.png)
> 
> ## 您帮忙再验证一下
> 您帮忙：
> 
> 1）新建一个聊天机器人 2）导入知识库：知识库 (2).json 【见上 知识库 (2).zip 解压 】 3）进入对话测试，发送 “东南亚航线有优惠吗”，并得到结果。
> 
> 您看是不是有关键词【优惠券】的问答对的分数比较高。
> 
> ![screenshot_20230417153238](https://user-images.githubusercontent.com/3538629/232415853-f1125aed-e0e7-4a77-8efa-99c3694260ed.png)
> 
> 对于您之前提到的这个返回结果：
> 
> 提问的问题： 东南亚航线有优惠吗
> 
> ```
> 你是不是想问以下问题？ -->
> 
> 如何查看是否有拼团价格？
> 如何线上对账？
> 如何在平台上完成订舱？
> 目前平台上有哪些服务产品？
> 如何获取并使用优惠券？
> 优惠券有哪些使用规则？
> 平台上会有哪些优惠活动？
> ```
> 
> 看上去是展示时，根据返回结果的 score 排序颠倒了。就是分数高的没有排到上面。 您的返回结果是怎么展示的。在 [对话检索](https://docs.chatopera.com/products/chatbot-platform/references/sdk/chatbot/chat.html) 接口中，都有 score 分数。
> 
> 如下：
> 
> ```
> {
> "id": "qo0PjocBgDTE2MpZ6San",
> "score": 0.42601,
> "post": "平台上会有哪些优惠活动？",
> "replies": [
> {
> "rtype": "plain",
> "enabled": true,
> "content": "平台上会有哪些优惠活动？"
> }
> ],
> ```
> 
> 结果的相关性是 score 越高，越和问题相似。

问题出现了，可以复现：如何线上对账，排在了上面。

![screenshot_20230417153835](https://user-images.githubusercontent.com/3538629/232417262-2fe796c1-2cef-410d-b74e-64f100d85a78.png)

**Comment by hailiang-wang** [comment]
服务重启后，继续排查，就无法复现了。可以得到正确的结果。

![screenshot_20230417161500](https://user-images.githubusercontent.com/3538629/232425981-be9785a3-a7ed-4467-a785-b6eb031cf847.png)

根据表现，是两个句子的相似度分数计算有的时候是正常的，有的时候不正常，根本原因在继续分析。
不正常的原因还需要确定，还需要排查。
问题解决后，会第一时间在本 Issue 更新，感谢您的配合反馈。

@halfray

**Comment by hailiang-wang** [comment]
该问题已经修正。

![screenshot_20230417193530](https://user-images.githubusercontent.com/3538629/232473001-3c7b3538-de30-4980-b54f-5492cb2a0658.png)

**Comment by halfray** [comment]
非常感谢，我们这边会对新的排序结果再进行验证
