### ISSUE TITLE
如何实现类似bing ，在回答问题后给予延伸问题的建议

### ISSUE THREAD

**Issue by halfray** [chatopera/docs#68]
## 概述

在new bing中进行提问后，会在答案后给予可能会进行追问的延伸问题的提示，在我们的系统中有什么方案可以实现该功能吗？

## 理想解决方案
   目前可以在相似问题上添加延伸问题的维护，知识库检索的时候将知识库信息和延伸问题都通过接口进行返回

![image](https://www.oksnl.com/testapi/minio/oksnl-mini/img/tmp/question.png)

**Comment by hailiang-wang** [comment]
目前使用 Chatopera 云服务，您就可以实现这样的交互效果。

首先，在多轮对话检索 API 中，是将 FAQ 的结果放在了返回数据中。[API](https://docs.chatopera.com/products/chatbot-platform/references/sdk/chatbot/chat.html#%E6%A3%80%E7%B4%A2%E5%A4%9A%E8%BD%AE%E5%AF%B9%E8%AF%9D)

![screenshot_20230421104600](https://user-images.githubusercontent.com/3538629/233528553-a798109f-5ec0-4a8b-9865-108e576ebcde.png)


其次，如果要更灵活的对每个知识库问答对自定义一个关联问题集，那么是使用多个答案的方式。设定一个答案，用于关联问题。比如，增加一个文本答案，约定一个 json 格式。

![screenshot_20230421104801](https://user-images.githubusercontent.com/3538629/233528793-f790a2c8-2dcd-4374-8dd0-6e984a4c15dd.png)

**Comment by hailiang-wang** [comment]
这个需求可以通过现在 Chatopera 已有的功能实现，但是还需要您在处理 API 返回结果时，做一些自定义的约定，以及您在交互渠道上识别这些约定，做展示。

**Comment by hailiang-wang** [comment]
在多轮对话检索 API 中，可以尽可能的利用返回值 faq 的数组，可以将建议回复的阈值设置 为 0，具体做法为：

设置 `faqSuggReplyThreshold = 0`

![screenshot_20230421120400](https://user-images.githubusercontent.com/3538629/233538287-84c39200-d408-4041-a389-379b83173b5b.png)



设置该参数的默认值，可以在控制台-设置中：

![screenshot_20230421120206](https://user-images.githubusercontent.com/3538629/233538156-c028c147-0918-42cb-af1b-5953327d1823.png)

**Comment by hailiang-wang** [comment]
为您推荐一个调试对话的开发者工具 

[https://docs.chatopera.com/products/chatbot-platform/howto-guides/chats/cli-connect.html](https://docs.chatopera.com/products/chatbot-platform/howto-guides/chats/cli-connect.html)

这个可以用来快速与机器人多轮对话交互，查看返回值。
