### ISSUE TITLE
如何在意图处理函数中获取this.message.extras

### ISSUE THREAD

**Issue by halfray** [chatopera/docs#76]
## 描述
通过春松客服向chatopera发送消息是都会携带extras信息，但是在对话函数中可以获取this.message.extras，但是在意图处理函数中获取的是undefined,请问如何获取?

**Comment by hailiang-wang** [comment]
我理解您的意思，但是您可否提供一个在 `意图处理函数中获取的是undefined` 您使用的代码片段，以让更准确的定位。感谢。

**Comment by hailiang-wang** [comment]
## 针对接口 

多轮对话 API [LINK](https://docs.chatopera.com/products/chatbot-platform/references/sdk/chatbot/chat.html#%E6%A3%80%E7%B4%A2%E5%A4%9A%E8%BD%AE%E5%AF%B9%E8%AF%9D)

```
Chatbot#command("POST", "/conversation/query", body)
```

body 中如果有 extras 信息：

![screenshot_20230504174944](https://user-images.githubusercontent.com/3538629/236171007-56019535-7915-4525-804b-2405e947656d.png)

**Comment by hailiang-wang** [comment]
新建 repo，对该问题进行复现和跟踪：

https://github.com/chatopera/Issue76
