### ISSUE TITLE
如何在意图识别中获取到用户问句的中的关键信息

### ISSUE THREAD

**Issue by halfray** [chatopera/docs#77]
## 概述

如果用户提问： 我想查询订单号为 xxx 的货物状态。
如何在意图识别中直接将xxx信息获取到？

目前是通过正则表达式词典来对用户进行追问获取xxx信息，但是系统不允许在用户说法中直接使用正则表达式字典。

## 理想解决方案
方案1 可以直接在用户说法中支持正则表达式字典
方案2 可以通过通配符匹配器对用户的信息进行匹配，匹配后跳转到指定意图，但是需要支持参数的传递

**Comment by hailiang-wang** [comment]
该问题后来您是怎么解决的？

**Comment by hailiang-wang** [comment]
您提及的两个方案都非常合理，

方案1 可以直接在用户说法中支持正则表达式字典

> 这个目前在产品上还不能很快支持

方案2 可以通过通配符匹配器对用户的信息进行匹配 ...

> 目前，这个已经部分实现

参考[在回复中跳转到指定意图](https://docs.chatopera.com/products/chatbot-platform/howto-guides/convs/conv-gambit-intent.html#%E5%9C%A8%E5%9B%9E%E5%A4%8D%E4%B8%AD%E8%B7%B3%E8%BD%AC%E5%88%B0%E6%8C%87%E5%AE%9A%E6%84%8F%E5%9B%BE), 该部分尚未实现的是，使用 `topicRedirect` 传入意图识别的参数。

![screenshot_20230508144618](https://user-images.githubusercontent.com/3538629/236753612-616bf96b-01c0-4e86-aeb5-26c7527b8917.png)

这个需要我们再做更多的思考，形成一个您能接受的方案。
