### ISSUE TITLE
请在SDK中添加自定义词典的词条管理

### ISSUE THREAD

**Issue by halfray** [chatopera/docs#78]
## 概述

目前系统需要匹配用户提供的港口信息，我们系统具备港口信息，但是数据量大且需要经常维护，如何通过SDK将这个信息同步到自定义词典中

**Comment by hailiang-wang** [comment]
好的，最晚下周一，您可以使用。 @halfray 

预计提供一下接口：

* 自定义词典创建
* 自定义词典列表查询
* 自定义词典删除
* 自定义词典词条
    * 增删改查
* 训练同步自定义词典（以下内容需要重新训练才能使用最新的自定义词典）
    * 训练API1：知识库重新训练
    * 训练API2：意图识别重新训练

重新训练会占用较多的资源，应在批量修改自定义词典后再调用训练接口。

**Comment by hailiang-wang** [comment]
@halfray 
您使用的 SDK 语言是哪个，我们优先支持该语言的 SDK 更新。

**Comment by hailiang-wang** [comment]
@halfray 目前，Chatopera 云服务是支持 CLI 批量管理机器人词典的。

刚刚补充了相关的文档，您看看这个能满足您的使用需求吗？

https://github.com/chatopera/issues/tree/main/issues/78


CLI 支持通过一个 JSON 文件管理，所以可以完成自动化任务。

在 CLI 中，本周提供 `bot faq -a train`。

**Comment by halfray** [comment]
目前使用的SDK语言是JAVA，请优先进行支持 @hailiang-wang

**Comment by hailiang-wang** [comment]
好的， 会先提供 Java。

实现自动化的自定义词典管理，CLI 仍然是您可以使用的一个方式。
刚刚也已经提供了 CLI 的知识库同步训练。

```
bot faq -a train
```

使用最新的 CLI 工具，只需要安装 [nodejs LTS ](https://nodejs.org/en/download) ：

```
npm install -g @chatopera/sdk
bot --version # 最新版 2.8.15
```

见 https://github.com/chatopera/issues/tree/main/issues/78

**Comment by hailiang-wang** [comment]
@halfray SDK 更新了，下面是说明。

## Chatopera Java SDK v3.5.2

* 支持自定义词典管理和词条管理
* 支持训练接口

### 示例 

* 词典管理：[DictsMgrTest](https://github.com/chatopera/chatopera-java-sdk/blob/3.5.2/src/test/java/com/chatopera/bot/sdk/DictsMgrTest.java)
* 训练管理：[TrainMgrTest](https://github.com/chatopera/chatopera-java-sdk/blob/3.5.2/src/test/java/com/chatopera/bot/sdk/TrainMgrTest.java)

要点：

* 使用[DictsMgr](https://chatopera.github.io/chatopera-sample-java/apidocs/com/chatopera/bot/sdk/DictsMgr.html)管理词典，对词典做了变更后，需要使用[TrainMgr](https://chatopera.github.io/chatopera-sample-java/apidocs/com/chatopera/bot/sdk/TrainMgr.html) 重新训练

### Apidocs

[Apidocs](https://chatopera.github.io/chatopera-sample-java/apidocs/com/chatopera/bot/sdk/package-summary.html)

### SDK 项目源码

https://github.com/chatopera/chatopera-java-sdk

**Comment by hailiang-wang** [comment]
@halfray 现在您使用该接口了吗？
现关闭本 issue，关于词典管理和训练 API 相关，如有使用问题，您可以创建新的 issue。
