### ISSUE TITLE
内置函数库中添加可以获取一句话中包含的词典信息

### ISSUE THREAD

**Issue by halfray** [chatopera/docs#79]
## 概述
 如果定义了食物这个词典，在用户发送的一句话中想要提取所有的涉及到的食物，该如何处理。

## 理想解决方案
可以通过添加一个提取字典信息的函数来完成。

**Comment by hailiang-wang** [comment]
## 解决方案

该支持会通过 `this.message.tags` 来支持：

比如，创建一个自定义的函数，使用 tags 来查询自定义词典的词条。

```
exports.getCustomDictnames = async function() {
    debug("words %j, %j", this.message.words, this.message.tags);
    return {
        text: "hello"
    }
}
```

## 现在表现 


脚本 - 


```
+ {keep} 测试词典 (*)
- ^getCustomDictnames()
```

函数 

```
exports.getCustomDictnames = async function() {
    debug("words %j, %j", this.message.words, this.message.tags);
    return {
        text: "hello"
    }
}
```

测试 `测试词典深圳`，得到 debug 信息

```
DEBUG   conversation  words ["测试","词典","深圳"], ["vn","n","ns"]
```

## 将来表现

假如，`深圳`在自定义词典 `cities` 中，那么 debug 输出应为

```
DEBUG   conversation  words ["测试","词典","深圳"], ["vn","n","gbcities"]
```

即：gb 开头的是自定义词典，`gb`后是词典的名称。


## 上线时间

这个需要检查一下，稍晚回复什么时候可以上线，也就是这几天。

**Comment by hailiang-wang** [comment]
@halfray 经过检查，现在平台已经支持在多轮对话函数中，获得自定义词语的词性。

与我之前描述的稍有不同，见下：

## 变更词条后，按照提示【完成一键同步】

![screenshot_20230511172634](https://github.com/chatopera/docs/assets/3538629/ec89723d-87eb-4762-b5ff-45c118f60660)

## 使用

脚本：

```
+ {keep} 测试词典 (*)
- ^getCustomDictnames()
```

如果在函数中，打印：

```
exports.getCustomDictnames = async function() {
    debug("words %j, %j", this.message.words, this.message.tags);
    return {
        text: "hello"
    }
}
```

结果：

![screenshot_20230511172715](https://github.com/chatopera/docs/assets/3538629/0f9e3624-9025-46e9-b283-28010d3f430e)

其中，`this.message.words` 是词语数组，`this.message.tags` 是词语数组对应的词性。

其中，对于自定义词典，词性值为【`g`词典标识名】, 比如以下的词性标识，就是：`gcities`, `gfruit`，这与前面评论中，我提到的`gb` 作为前缀不同，正确的前缀是 `g`。

![screenshot_20230511173209](https://github.com/chatopera/docs/assets/3538629/50fbeb07-338d-4460-8f92-eb3efe844f26)


如果以上已经满足了您的需求，请关闭或反馈，感谢。

**Comment by hailiang-wang** [comment]
内置函数库提供了 `_` 包，可以快速的遍历分词信息，


`_` 包的介绍：[LINK](https://docs.chatopera.com/products/chatbot-platform/references/func-builtin/basics.html#_)

比如在 `getCustomDictnames` 中，使用 zip：

```
exports.getCustomDictnames = async function() {
    debug("words %j, %j", this.message.words, this.message.tags);

    let terms = _.zip(this.message.words, this.message.tags);

    for (let i in terms) {
        debug("No. %d, word %s, tag %s", i, terms[i][0], terms[i][1]);
    }

    return {
        text: "hello"
    }
}
```

**Comment by halfray** [comment]
似乎无法区分正则表达式定义的词典

**Comment by halfray** [comment]
另外，目前只能识别是哪个词典吗，可以进一步识别出是哪个词条吗？

**Comment by halfray** [comment]
可以，期待处理后的结果

**Comment by hailiang-wang** [comment]
@halfray 现在已经完成了以下功能

## message.words 和 message.tags 的 BUG 修正
* 上周发现的数据的 BUG，已经修正

## this.message 中支持获得词表词典的标准词

如果在用户的发送的文本中，包含在自定义词条的词条中，那么现在支持了通过 `this.message.lemms` 返回对应的标准词。

this.message.lemms 是对应 this.message.words 的词根。

比如：

1）存在这样的自定义词典 

![screenshot_20230516115107](https://github.com/chatopera/docs/assets/3538629/e371822a-c6ae-4cfa-af37-ee8464f8f2be)


2）在多轮对话函数中，设置函数和脚本

函数

```
exports.getCustomDictnames = async function() {
    debug("words %j, %j, %j", this.message.words, this.message.tags, this.message.lemms);

    let terms = _.zip(this.message.words, this.message.tags, this.message.lemms);

    for (let i in terms) {
        debug("No. %d, word: %s, tag: %s, lemm: %s", i, terms[i][0], terms[i][1], terms[i][2]);
    }

    return {
        text: "hello"
    }
}
```

脚本

```

+ {keep} 测试词典 (*)
- ^getCustomDictnames()
```


3）发送对话文本

```
测试词典土豆
```

那么，函数中打印的结果是

```
2023-05-16 11:47:26   DEBUG   conversation  words ["测试","词典","土豆"], ["vn","n","gfruit"], ["测试","词典","马铃薯"]
2023-05-16 11:47:26   DEBUG   conversation  No. 0, word: 测试, tag: vn, lemm: 测试
2023-05-16 11:47:26   DEBUG   conversation  call getCustomDictnames:
2023-05-16 11:47:26   DEBUG   conversation  No. 2, word: 土豆, tag: gfruit, lemm: 马铃薯
2023-05-16 11:47:26   DEBUG   conversation  No. 1, word: 词典, tag: n, lemm: 词典
2023-05-16 11:47:26   DEBUG   conversation  call getCustomDictnames result: { text: 'hello' }
```

所以，message.lemms 是词根信息，根据自定义词典，马铃薯（标准词）是土豆（近义词）的词根。

**Comment by hailiang-wang** [comment]
@halfray , 刚刚支持了 提取正则表达式词典的内置函数，具体使用见下：

## 定义正则表达式词典

正则表达式词典使用： [使用文档](https://docs.chatopera.com/products/chatbot-platform/howto-guides/dicts/dicts-regex.html#%E5%B8%B8%E7%94%A8%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F)

假设建立了一个正则表达式词典，用以提取邮箱信息。

![screenshot_20230516134403](https://github.com/chatopera/docs/assets/3538629/d3ea0d59-07f7-402b-9f68-f6ad2ee8fa7c)

## 脚本和函数

多轮对话脚本如下：

```
+ {keep} 测试正则词典 (*)
- ^getCustomRegexDictnames()
```

函数：

```
exports.getCustomRegexDictnames = async function() {
    debug("this.message.original %s", this.message.original)
    let matches = await this.maestro.extractRegexDicts(this.message.original);
    debug("[extractRegexDicts] matches %j", matches);

    return {
        text: "hello "
    }
}
```

说明：` await this.maestro.extractRegexDicts` 此处的使用，其返回值结构见下。

```
{
    "词典标识": [
        {
            "val": 匹配值,
            "begin": 开始位置,
            "end": 结束位置,
        }
    ]
}
```

## 验证

在多轮对话设计器，对话测试窗口发送：`测试正则词典doo@cc.com`

![screenshot_20230516153335](https://github.com/chatopera/docs/assets/3538629/cb24c9bf-b1dc-4689-9798-aade0f2944e5)

调试窗口得到日志：

```
2023-05-16 15:27:44   DEBUG   conversation  this.message.original 测试正则词典doo@cc.com
2023-05-16 15:27:44   DEBUG   conversation  [extractRegexDicts] matches {"email":[{"begin":18,"end":28,"val":"doo@cc.com"}]}
```

![screenshot_20230516153131](https://github.com/chatopera/docs/assets/3538629/1c67bc85-b039-40be-9ecb-aec7b0773899)





```

```

**Comment by hailiang-wang** [comment]
本 issue 关联了两个功能，目前都已实现。
每个 issue 尽量是针对独立的问题，因 issue 中消息较多，不方便维护，现关闭。
后续相关问题请使用新的 issue 反馈。感谢。
