### ISSUE TITLE
未优先匹配意图而匹配到知识库信息

### ISSUE THREAD

**Issue by halfray** [chatopera/docs#80]
定义了一个意图： goods_state， 用户说法定义为 ： 查询货物状态
在 多轮对话设计器中定义了该意图的处理方法
```
 intent {keep} goods_state
 ^query_goods_state()
 ```

现在在对话框中输入 查询货物状态，结果并未走意图处理函数，而是在知识库中匹配到了相似的内容

这是debug信息:
```
2023-05-12 10:36:55   DEBUG   conversation  [query] conversation request { "textMessage": "查询货物状态", "faqSuggReplyThreshold": 0.1, "fromUserId": "5784d9fa6535b080a7a8b57d695408e6", "extras": { "userNo": "SSDCW01" }, "faqBestReplyThreshold": 0.7 }

2023-05-12 10:36:55   DEBUG   intent  analysis branch(dev) name(score): goods_state(1) | threshold 0.9

2023-05-12 10:36:55   DEBUG   faq  Chatbots middlewares faq: check against faqBestReplyThreshold(0.7), faqSuggReplyThreshold(0.1)

2023-05-12 10:36:55   INFO   faq  Chatbots middlewares faq: matched, ctx.response = { "string": "
xxxxxxxxx
```

我的clientId为: 641801eab1fcf4001379a113

**Comment by hailiang-wang** [comment]
看起来是 goods_state(1) ，代表该对话输入（查询货物状态）已经匹配上了（1 代表置信度是 1）。
预计下周可以解决。

**Comment by halfray** [comment]
目前该问题依然存在，请尽快修复

**Comment by hailiang-wang** [comment]
这两天正在解决，预计本周可以完成升级。感谢您的耐心等待。

**Comment by hailiang-wang** [comment]
@halfray ，现在更新了，意图匹配器的优先级排在 FAQ 前面。

对于已有的机器人，您需要先在多轮对话设计器中，对机器人进行一次【保存】，才会使用以下功能。

![screenshot_20230519134723](https://github.com/chatopera/docs/assets/3538629/9e981d99-d916-45cd-a049-f536039c4154)



具体说明如下：

## 对话

### 存在意图识别和意图匹配器

![screenshot_20230519134421](https://github.com/chatopera/docs/assets/3538629/17088893-91c9-4f87-b0bd-cc5cd64ff8cd)

函数和脚本：

```
intent goods_state
- ^query_goods_state()
- {x} ^query_goods_fal_state()

# 函数
exports.query_goods_state = async function() {

    debug("intent", this.intent)

    return {
        text: "意图识别 DONE"
    }
}

exports.query_goods_fal_state = async function() {

    debug("intent", this.intent)\
    // 主动丢弃
    this.intent.drop = true;

    return {
        text: "意图识别 FA"
    }
}
```

### 知识库


![screenshot_20230519134555](https://github.com/chatopera/docs/assets/3538629/1a55a159-bf43-4b8c-be71-58cd37c53355)



## 逻辑

如果此时，在多轮对话中发送：`查询货物状态`，会匹配到意图会话。


![screenshot_20230519134302](https://github.com/chatopera/docs/assets/3538629/65884dcf-56ed-4157-bf72-12c5c00b0905)


### 当意图追问后，用户的回答没有匹配到槽位时

此时，会重复追问，直到达到了意图对话的最大追问次数，见【机器人-设置-多轮对话意图对话最多追问次数】


![screenshot_20230519134831](https://github.com/chatopera/docs/assets/3538629/b5e00c6a-a6a1-4716-8ca4-b2b6b9d75f2f)


达到了最大的追问次数，如果存在【意图会话-失败函数】，（[什么是失败函数?](https://docs.chatopera.com/products/chatbot-platform/howto-guides/convs/conv-gambit-intent.html#%E6%84%8F%E5%9B%BE%E5%8C%B9%E9%85%8D%E5%99%A8%E5%8F%96%E5%80%BC)）, 那么会执行失败函数，否则继续调用知识库和多轮对话。

但是意图识别还是在等待识别槽位，在后续的对话中，还会追问，除非：

1）超时，[参考文档](https://docs.chatopera.com/products/chatbot-platform/howto-guides/convs/conv-gambit-intent.html#%E7%A9%BA%E9%97%B2%E6%97%B6%E9%97%B4%E5%A4%AA%E4%B9%85%E8%80%8C%E8%BF%87%E6%9C%9F)
2）在失败函数中调用 `this.intent.drop = true`


多轮对话中使用意图匹配器，是一个比较强大但相对又复杂的应用，敬请您详细阅读使用文档：

https://docs.chatopera.com/products/chatbot-platform/howto-guides/convs/conv-gambit-intent.html

期待继续得到您的反馈。

**Comment by hailiang-wang** [comment]
本 issue 带您确认解决后，请关闭。感谢。
@halfray

**Comment by halfray** [comment]
测试了一下，并没有解决，还是会出现直接返回知识库的情况，偶尔会匹配到意图
![bug](https://github.com/chatopera/docs/assets/8181982/de638274-ab3f-4c16-9caa-a138f43e8779)

**Comment by halfray** [comment]
目前同时匹配意图和知识库的逻辑比较难理解
![bug](https://github.com/chatopera/docs/assets/8181982/f6005c5b-d830-4bb9-aa7e-fbfbd367671e)
如上图所示，第一次提问，命中了意图，但是我处理函数里没提示用户未登录，需要进行登录操作。此时这次意图识别结束了。
当我再次输入货物状态查询时，应该再次命中意图，但是却命中了知识库，而且后面都是命中知识库不再命中意图了。

**Comment by halfray** [comment]
目前即使和意图无关的提示也会命中意图  ，日志如下：


2023-05-19 17:08:11   DEBUG   conversation  [query] conversation request { "fromUserId": "superadmin", "textMessage": "测试词典JLMF00200" }

2023-05-19 17:08:11   DEBUG   intent  analysis branch(dev) name(score): goods_state(0.038461538461538436) | threshold 0.9

![bug2](https://github.com/chatopera/docs/assets/8181982/45dc6ab4-5800-4247-93e2-a1b6088eb3a5)

**Comment by hailiang-wang** [comment]
收到，今天稍后进行测试，会尽快的升级。

**Comment by halfray** [comment]
![bug3](https://github.com/chatopera/docs/assets/8181982/581a4072-2ad0-4351-b66f-79c8c1b9753c)
这种设计有待商榷，在一个意图中，如果用户的回答匹配到了其他的信息，这时这个意图应该中断而不应该保持。
因为用户无法感知现在是不是在一个意图对话中，尤其在意图中进行多轮对话后，用户就会忘记自己最开始的问题。

**Comment by hailiang-wang** [comment]
> 这种设计有待商榷，在一个意图中，如果用户的回答匹配到了其他的信息，这时这个意图应该中断而不应该保持。 因为用户无法感知现在是不是在一个意图对话中，尤其在意图中进行多轮对话后，用户就会忘记自己最开始的问题。

您说的有道理，也就是：每次追问没有得到目标的信息，则丢弃当前进行中的意图会话。
该逻辑没有成为默认的逻辑，原因是很难把握聊天机器人开发者们的应用需求。

Chatopera 更是希望让产品本身能“配置”，以符合需要，灵活处理。

如果您希望当前进行中意图对话，没有得到追问信息旧丢弃，那么可以：

1）设置最大追问次数为 1

![screenshot_20230519174353](https://github.com/chatopera/docs/assets/3538629/a9ad2e10-51ba-45c9-84d2-a3280066b4c7)

2）在该意图的意图匹配器中，不提供【失败函数】

那么，就会自动的检索 FAQ 和其它的多轮对话脚本。

**Comment by hailiang-wang** [comment]
> 目前即使和意图无关的提示也会命中意图 ，日志如下：
> 
> 2023-05-19 17:08:11 DEBUG conversation [query] conversation request { "fromUserId": "superadmin", "textMessage": "测试词典JLMF00200" }
> 
> 2023-05-19 17:08:11 DEBUG intent analysis branch(dev) name(score): goods_state(0.038461538461538436) | threshold 0.9
> 

目前，该问题已经修正，只有 意图分数高于 阈值（threshold）才会开始意图会话。

**Comment by halfray** [comment]
确认已解决
