### ISSUE TITLE
系统提示 ： 返回结果异常，系统错误

### ISSUE THREAD

**Issue by halfray** [chatopera/docs#81]
## 现在行为
我的clientId 为 63db4aeaac2af00013031462 ,目前测试输入 查询订单状态 ，系统无法返回结果，只会提示：返回结果异常，系统错误

**Comment by hailiang-wang** [comment]
很抱歉出现这样的问题，明天上午为您解决。

**Comment by halfray** [comment]
目前对话返回结果要么没有返回，要么返回慢，请尽快解决，并希望后期能保证正式环境的稳定性，否则对业务环境的影响较大。

**Comment by hailiang-wang** [comment]
昨天的服务异常，是出现了一个子节点奔溃。
该子节点关联：词典管理、意图管理。
该节点奔溃会导致多轮对话请求的异常。

现在还在排查，初步推测是因为在短时间内请求量大于系统负载能力导致的。

**Comment by hailiang-wang** [comment]
> 目前对话返回结果有些是没有返回，有些返回慢，请尽快解决，并希望后期能保证正式环境的稳定性，否则对业务环境的影响较大。

您的请求有时候有返回值，有的没有返回值，这些请求是相同的内容吗？

**Comment by halfray** [comment]
我的clientId 为63db4aeaac2af00013031462 ，输入 查询货物状态，统无法返回结果，只会提示：返回结果异常，系统错误
查询知识库问题，有些有返回，有些没有返回或返回慢。比如输入：请问平台可以查询哪里的价格

**Comment by hailiang-wang** [comment]
1）对话结果没有返回：请确认您的语料是存在，导入了的。因为昨天服务节点崩溃，可能导致相应的数据没有导入。

2）请求返回结果慢：昨天在生产环境为了排查问题，提升了日志的输出，现在又调整了日志级别，现在返回速度提升了，您确认一下，当前返回结果还慢吗？

以上的两个问题，1）的根本原因是系统的负载存在压力的上限，即每秒最多请求的次数限制，也称为 rate limit，一般以 qps （每秒支持请求次数）来衡量。比如 [github api rate limits](https://docs.github.com/en/apps/creating-github-apps/setting-up-a-github-app/rate-limits-for-github-apps), rate limit 在 Chatopera 云服务上没有监控和限制，但是存在硬件上的客观限制，对于 CUD（Create，Update，Delete）相关的 APIs，小于 10 qps 请求是能保证数据一致性的。相对对话检索接口，其类型主要是 Read，小于 20 qps 能保证正常服务。

**Comment by halfray** [comment]
对于输入的内容是 “查询货物状态”，对应的意图目前在系统后台还是可以查询到，但是在多轮对话设计器中进行测试，只有返回结果异常，系统错误。

而输入  “请问平台可以查询哪里的价格” 或者 “平台为何查询不到 (*) 航线价格”  对应的是应该是知识库中的信息，目前在后台也是可以看到的，但是目前也是报 结果异常，系统错误。

目前返回结果慢的问题的问题可能是因为问了上面的问题后没有返回结果，然后追问其他问题导致的，请优先解决 返回结果异常的情况。

**Comment by halfray** [comment]
目前该问题依然存在，请尽快修复

**Comment by halfray** [comment]
目前 clientid 为 641801eab1fcf4001379a113的账户也出现这个问题，如果询问: 如何查询/下载电子发票,  第一次返回正常，第二次询问就会报 “ 返回结果异常，系统错误。”

**Comment by hailiang-wang** [comment]
好的，预计本周解决。

**Comment by hailiang-wang** [comment]
@halfray 您好，该问题已经解决。最终排查后发现，是代码中的 BUG 导致。

待您验证没有问题后，请关闭本 Issue。

关于服务稳定性保证，见 [https://docs.chatopera.com/products/chatbot-platform/contract/sla.html](https://docs.chatopera.com/products/chatbot-platform/contract/sla.html).

**Comment by halfray** [comment]
确认已解决
