### ISSUE TITLE
[意图会话] 如何在函数中，关闭或放弃正在进行中的意图会话

### ISSUE THREAD

**Issue by hailiang-wang** [chatopera/docs#82]
目前同时匹配意图和知识库的逻辑比较难理解
![bug](https://github.com/chatopera/docs/assets/8181982/5309de70-a8c6-4eff-9f49-79de1add4e20)

如上图所示，第一次提问，命中了意图，但是我处理函数里没提示用户未登录，需要进行登录操作。此时这次意图识别结束了。
当我再次输入货物状态查询时，应该再次命中意图，但是却命中了知识库，而且后面都是命中知识库不再命中意图了。

_Originally posted by @halfray in https://github.com/chatopera/docs/issues/80#issuecomment-1554264612_

**Comment by hailiang-wang** [comment]
@halfray 这个问题是一个不同于 #80 的问题，我创建了新的 issue 跟踪讨论，优化。
您的反馈我认真的思考一下，欢迎提供合理的方案，就是您的业务需求在此情况下，怎么处理比较好。

**Comment by hailiang-wang** [comment]
@halfray 根据您提供的对话截图，这个对话的目标是：


## 期望目标

1）在识别意图【货物状态查询】后，追问槽位【提单信息】，在获得提单信息后，进入【成功函数】，比如是 `query_goods_state`

2）在成功函数 `query_goods_state` 中，检查是否完成了登录，没有登录的话，返回 `未登录`，这时候客户端会弹出登录窗口

3）登录完成，访客在聊天窗口再次发送：【货物状态查询】可以再次进入意图识别。

## 目前的表现

上述 1，2） 两步骤可以正常进行，但是 3）步骤总是进入知识库匹配的回答。

## 解决方案

在这个场景中，在第 3 步未能正常进行，在于【成功函数】未能清空当前的【意图会话】信息，即在意图对话中调用：`this.intent.drop = true`。

所以，您的成功函数应类似这样：


```
exports.query_goods_state = async function(){
        if (this.message.extras && this.message.extras['userid']) {
             // 具备了用户登录信息
             // 处理逻辑 

             // 逻辑完成，关闭当前意图会话
             this.intent.drop = true;    // 位置1
             // 返回货物信息
             return { text: "{CLEAR} 货物信息 xxx"}
        } else {
             // 没有用户登录信息
             // 丢弃当前意图会话
             this.intent.drop = true;   // 位置2

             // 返回登录
             return { text: "{CLEAR} 未登录"}
        }
}
```

注意：
* 位置1  `this.intent.drop` 不能省略，因为此处代表意图满足了业务执行的需求，可以返回货物信息，该流程结束。
* 位置2 `this.intent.drop = true` 不写，那么随后进行的多轮对话的函数中，仍然可以用 `thisl.intent` 获得当前的意图会话的信息，直至函数中执行 `this.intent.drop = true`。

## 设计的初衷

为什么是这样？因为此处的设计思路是：意图匹配器完成后会调用【成功函数】或【失败函数】，此时代表意图匹配器识别了意图以及（全部或部分）槽位信息。现在聊天机器人和请求的访客处在该意图对话的处理阶段，就是在【成功函数】和【失败函数】中，完成利用槽位信息完成意图的相关工作。

那么，意图会话什么时候退出呢？这就需要按照业务的逻辑，Chatopera 将该行为给聊天机器人开发者自己决定：什么时候调用 `this.intent.drop = true`。

**Comment by hailiang-wang** [comment]
# 使用 `this.intent` 优化对话

此外，在 位置2 如果不调用  `this.intent.drop = true`，那么可以在访客登录后，再发送给机器人一个对话，来完成信息的查询。
此时，就不需要访客登录后，重复进行意图识别。

以下为这种实现的说明：

## 脚本 

示例：

```
intent {keep} goods_state
- ^query_goods_state()

// 登录后，给机器人发送文本：goods_state_postlogin
+ {keep} goods_state_postlogin
- ^query_goods_state()

```

## 函数

示例：

```

// 查询货物状态
exports.query_goods_state = async function(mblNo, cb) {
    if (this.message.extras && this.message.extras['userNo']) {
        let userNo = this.message.extras['userNo']
        this.intent.drop = true;     // 位置 1
        
        debug("获取到登录的用户为:", userNo)
        // 其它逻辑 ...

            return {
                text: `货物状态信息`,
                params: {
                    xxx: "xxxx",
                }

        }
    } else {
        return {
            text: "{CLEAR} 未登录",
            params: {
                type: 'html',
                text: `登录 ...`,
                forward: "goods_state_postlogin"   // 提示：此处自定义了一个字段，作为登录成功后，约定的多轮对话入口
            }
        }
    }
}
```

**Comment by hailiang-wang** [comment]
@halfray 您看上述介绍 `this.intent.drop = true` 的使用可以满足您的应用场景吗？

**Comment by halfray** [comment]
可以 ，能够满足当前场景的需要
