### ISSUE TITLE
意图识别中未正确匹配到插槽中的值

### ISSUE THREAD

**Issue by halfray** [chatopera/docs#83]
## 现在行为
我的clientId 为641801eab1fcf4001379a113的账户，进行设置的意图goods_state，并绑定了词典 mbl_list ,mbl_list中设置了词典项：YZJ2215ENBIH133 ，但是进行测试时并没有匹配上

![bug](https://github.com/chatopera/docs/assets/8181982/ce9bf123-de3d-4a6a-8b44-78f0561c1cec)

**Comment by hailiang-wang** [comment]
感谢反馈，预计本周内解决，完成升级。

**Comment by hailiang-wang** [comment]
@halfray 该问题未能重现，测试过程如下: 

## 词典

![screenshot_20230523161000](https://github.com/chatopera/docs/assets/3538629/797e22c6-d0b5-4709-b9f1-271e66403122)

点击【一键同步】并等待完成。

## 脚本和函数

```
// 脚本 

intent {keep} goods_state
- ^query_goods_state()

// 函数
exports.query_goods_state = async function() {
    debug('意图识别信息: this.intent %j', this.intent);
    return "未登录"
}
```


保存，脚本和函数。


## 进行测试

发送：`查询货物状态` - `请输入提单号` - `YZJ2215ENBIH133`, 得到如下回复：

```
2023-05-23 16:12:14   DEBUG   conversation  意图识别信息: this.intent 
{
  "name": "goods_state",
  "topicName": "intents",
  "branch": "dev",
  "entities": [
    {
      "name": "mbl",
      "val": "YZJ2215ENBIH133",
      "requires": true,
      "dictname": "mbl_list"
    }
  ],
  "candidates": [
    {
      "chatbotID": null,
      "name": "goods_state",
      "id": null,
      "description": null,
      "createdate": null,
      "updatedate": null,
      "score": 0.9
    }
  ],
  "extras": {},
  "state": "resolved"
}
```


![screenshot_20230523161408](https://github.com/chatopera/docs/assets/3538629/0385506e-a748-480c-8d93-8d11ce251658)

## 可能的问题

在您更新词典后，有没有进行词典同步任务，需要执行操作如 #84

**Comment by halfray** [comment]
词典同步任务已执行，目前依然存在该问题，可以使用我的clientId :641801eab1fcf4001379a113  进行测试

**Comment by hailiang-wang** [comment]
@halfray 该问题已经解决，原因是单个自定义词典设定了最大的词条数：10,000 条。先该数字调整为 1 千万。

目前，已经在您的 clientId 的 bot 上重新同步词典。您可以调整词典后，再次同步，确认问题是否存在。

另外，Java SDK 发布了新版本 3.5.4，更新了：
* 同步词典时强制执行
* 优化检查状态接口

## SDK 源码

https://github.com/chatopera/chatopera-java-sdk

## 或使用 Maven POM

pom.xml 增加 repo
```
    <repositories>
        <repository>
            <id>chatopera</id>
            <name>Chatopera Inc.</name>
            <url>https://nexus.chatopera.com/repository/maven-public</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```

pom 中添加依赖。

```
<dependency>
  <groupId>com.chatopera.bot</groupId>
  <artifactId>sdk</artifactId>
  <version>3.5.4</version>
</dependency>
```

**Comment by halfray** [comment]
经测试目前问题已解决，非常感谢
