### ISSUE TITLE
[dicts] message.words 和 message.tags 进行词典匹配没有使用自定义词典

### ISSUE THREAD

**Issue by halfray** [chatopera/docs#84]
## 现在行为
测试代码:
`debug("words %j, %j", this.message.words, this.message.tags);`
输入的内容：
SOCCQDTL171671
返回的结果：
2023-05-22 09:50:07   DEBUG   conversation  words ["测试","词典","soccqdtl","171671"], ["vn","n","nx","m"]

## 预期行为
SOCCQDTL171671 为设置的词典项，并未匹配
![bug](https://github.com/chatopera/docs/assets/8181982/7ddaa9d8-b059-4f46-b1d7-e12639c00fb9)

clientId: 641801eab1fcf4001379a113

**Comment by hailiang-wang** [comment]
感谢反馈，预计这个问题在本周三之内可以完成升级。

**Comment by hailiang-wang** [comment]
@halfray 

该问题无法重现，在测试过程中：

## 创建词典和脚本

词典: 

![screenshot_20230523152202](https://github.com/chatopera/docs/assets/3538629/7a385e0f-b1fa-4395-86ef-1115341d9cf4)


脚本和函数

```
# 脚本

+ {keep} 测试词典 (*)
- ^query_goods_state_tag()

# 函数
exports.query_goods_state_tag = async function() {
    debug("this words: %j, this.tags %j, this.lemms %j", this.message.words, this.message.tags, this.message.lemms)
    return "Hello"
}

```



## 发送测试

发送：`测试词典 SOCCQDTL171671` 或 `测试词典SOCCQDTL171671`。这两个的区别是前者增加了一个空格

![screenshot_20230523151929](https://github.com/chatopera/docs/assets/3538629/7fd51a38-75e7-4887-ab98-7844fe8e8f04)

如上图，得到的结果是符合预期的:

```
conversation  this words: ["测试","词典","soccqdtl171671"], this.tags ["vn","n","gmbl_list"], this.lemms ["测试","词典","soccqdtl171671"]
```

## 可能的问题

在批量更新自定义词典后，可以在控制台-词典管理，看到这样的提示：一键同步。

![screenshot_20230523152451](https://github.com/chatopera/docs/assets/3538629/7ca00f68-4ab2-4924-9a4e-f807c3cd9781)

您是否执行了一键同步？

相关的 API 接口：https://github.com/chatopera/chatopera-java-sdk/blob/2428a3b906949e45b15f0661d2d29111d1e271e9/src/test/java/com/chatopera/bot/sdk/TrainMgrTest.java#LL91C1-L91C1

**Comment by hailiang-wang** [comment]
同步词典的任务完成后，您可以看到类似的提示：

![screenshot_20230523152941](https://github.com/chatopera/docs/assets/3538629/b71176a0-c646-4dab-9a04-740b5655ed88)

**Comment by hailiang-wang** [comment]
@halfray 如您提供 clientId，可以帮您看一下这个机器人的数据，看看是什么原因。感谢。

**Comment by halfray** [comment]
clientId: 641801eab1fcf4001379a113

**Comment by hailiang-wang** [comment]
@halfray 在您给定的机器人上测试，没有重现问题。

这是刚刚的测试过程和结果。

## 检查该机器人的状态

以下使用 java SDK，[参考](https://github.com/chatopera/chatopera-java-sdk/blob/998d3513045f26ec8623df6bb6acef5c65a77e30/src/test/java/com/chatopera/bot/sdk/TrainMgrTest.java#L49)

```
      Status s = this.trainMgr.getStatus();
```

得到多轮对话、意图识别、脚本都是和词典同步的。

![screenshot_20230524111035](https://github.com/chatopera/docs/assets/3538629/fd77e593-5dba-43a6-9a9c-7035e7ef83d4)

关于 `retrain`, `reindex`, `reparse` 的含义，见 [Status.java](https://github.com/chatopera/chatopera-java-sdk/blob/998d3513045f26ec8623df6bb6acef5c65a77e30/src/main/java/com/chatopera/bot/sdk/models/Status.java#L27).

一个主要的状态码含义，如果上面的  `retrain`, `reindex`, `reparse`  值都是 0，则代表同步。

## 在多轮对话设计器中添加机器人

发送测试 `测试词典SOCCQDTL171671`，从日志中得到的返回结果符合预期。

![screenshot_20230524110428](https://github.com/chatopera/docs/assets/3538629/01d10358-a574-473b-895d-49e7e9c822cb)

## 推测 

监狱现在的返回值是正确的，可能您在测试时，词典和对话技能（FAQ、多轮对话、意图识别）并未同步。

**Comment by hailiang-wang** [comment]
如果这个问题再次出现，您可以用 ` Status s = this.trainMgr.getStatus();` 查看一下 Status 中的值：

```
        Status s = this.trainMgr.getStatus();
        System.out.println("getReindex " + Integer.toString(s.getReindex()));
        System.out.println("getReparse " + Integer.toString(s.getReparse()));
        System.out.println("getRetrain " + Integer.toString(s.getRetrain()));
```

如果以上值都是 0，则 BUG 存在。
如果以上存在不为 0 的值，则需要调用以下代码后，再次测试：

```
        // 提交训练任务
        this.trainMgr.trainAll();
        // 等待训练结束
        this.trainMgr.waitForJobsDone();
```

测试还存在问题，则属于 BUG。

**Comment by hailiang-wang** [comment]
@halfray 

以上测试来自于 clientId 63db4aeaac2af00013031462。

正在为您查看 ClientId 641801eab1fcf4001379a113。

**Comment by halfray** [comment]
目前测试结果如下，词典中的词被失败为gkuai8，是什么含义，我的词典中没有kuai8这个词典
![bug](https://github.com/chatopera/docs/assets/8181982/66c189c7-a11b-4f11-9a96-554754be3fbc)

**Comment by hailiang-wang** [comment]
看上去是分词结果出错，和本 issue 的原因有所不同。
分词错误将在 https://github.com/chatopera/docs/issues/85 中解决。
预计本周内可以解决，现在就排查详情，对存在的 BUG 深表歉意。

**Comment by halfray** [comment]
目前状态都已经是同步的
![bug](https://github.com/chatopera/docs/assets/8181982/55f4fdb3-e6bf-426e-a02d-21d67ade5fff)

但是再次测试，又回到了原来的状态，还是没识别出词典
![bug1](https://github.com/chatopera/docs/assets/8181982/f4f5f9bd-5cbd-4778-b217-574f81abaf5c)

**Comment by hailiang-wang** [comment]
@halfray 
您上面的 clientId 是 641801eab1fcf4001379a113 ？这个是分词词典加载问题，正在解决。

**Comment by halfray** [comment]
clientId还是 63db4aeaac2af00013031462 出现的问题

**Comment by hailiang-wang** [comment]
Duplicated with https://github.com/chatopera/docs/issues/85 

经排查发现和 #85 是同一原因。在 #85 中解决。

**Comment by halfray** [comment]
确认问题已解决，非常感谢
