### ISSUE TITLE
[dicts] 目前测试结果如下，词典中的词被失败为gkuai8，是什么含义，我的词典中没有kuai8这个词典

### ISSUE THREAD

**Issue by hailiang-wang** [chatopera/docs#85]
目前测试结果如下，词典中的词被失败为gkuai8，是什么含义，我的词典中没有kuai8这个词典
![bug](https://github.com/chatopera/docs/assets/8181982/66c189c7-a11b-4f11-9a96-554754be3fbc)

_Originally posted by @halfray in https://github.com/chatopera/docs/issues/84#issuecomment-1560523348_

**Comment by hailiang-wang** [comment]
@halfray 该问题刚刚解决并升级完成。

经排查，该问题的原因是分词器词典初始化时，在多线程访问中同时进行了初始化，造成了脏数据。
现在已经优化解决。

**Comment by halfray** [comment]
测试问题已解决，非常感谢
