### ISSUE TITLE
知识库文件导入相同问题时，没有过滤掉相同的问题，导致知识库里存在多条相同的问题

### ISSUE THREAD

**Issue by kely33** [chatopera/docs#90]
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

**Comment by hailiang-wang** [comment]
目前，Chatopera 云服务判断，是否是同一个问题时，依据的是 docId, 即 excel 的第一列。

<img width="428" alt="screenshot_20230606105821" src="https://github.com/chatopera/docs/assets/3538629/1adf670d-e48a-49f1-ba1e-527a7e5be902">

这样便于更新问题，重新导入，所以并不以文本为依据。

您可以在 excel 中，对同一个问题使用相同的 docId，对于从 Chatopera 云服务导出的 知识库 excel 会带有生成的 docId。

<img width="502" alt="screenshot_20230606105945" src="https://github.com/chatopera/docs/assets/3538629/8d7fc8c0-68cf-47c2-8c23-5cf27806dcb1">

建议您在知识库 excel 上携带有 docId，该值为字符串长度小于等于 32 的由字母和数字组成。

**Comment by hailiang-wang** [comment]
您可以借助在线工具生成每个【问题】的 docId
https://uutool.cn/hash/

粘贴问题，点击 MD5

<img width="508" alt="screenshot_20230606110352" src="https://github.com/chatopera/docs/assets/3538629/fec80884-6ae9-4d1c-b8a5-08168b585ad0">

复制结果，即 docId

<img width="426" alt="screenshot_20230606110446" src="https://github.com/chatopera/docs/assets/3538629/98f67938-cb5e-4209-8177-7c4271bc64f2">

该方法，对于文本一样的内容，将生成唯一的 ID。

**Comment by kely33** [comment]
那如果说，我们再导入文件时，问题1的id和问题2的id手误输入一样了，那导进去的问题会是哪个问题

**Comment by hailiang-wang** [comment]
对于同一个 docId，生效的是最后一次导入的那个问题。
docId 是区分一个问答对的唯一标识，而不是【问题】。

**Comment by kely33** [comment]
好的，了解了，感谢答疑！！

**Comment by hailiang-wang** [comment]
感谢您的反馈，建议是每次导入后，再导出，然后维护这个文件，因为：
* 导出后得到 docId
* 利用 excel 的排序和查找功能
* 利用 excel 批量操作
* 在 excel 中，如果您要新添加的问题还没有，则追加新的问题和答案即可，不需要创建 docId，导入后再导出会自动为新的问答对生成 docId

**Comment by kely33** [comment]
好的，谢谢建议
