### ISSUE TITLE
意图识别可以实现用户通过机器人订票的闭环吗

### ISSUE THREAD

**Issue by kely33** [chatopera/docs#91]
如果我要用chatOpera的【意图识别】去完成一个订票服务，那么意图识别可以实现用户通过机器人订票的闭环吗？

**Comment by hailiang-wang** [comment]
您说闭环，我理解是：1）训练意图识别模型；2）有用户与聊天机器人的渠道；3）识别用户的意图后，处理用户的意图。

以上都可以在 Chatopera 云服务实现：https://bot.chatopera.com

1）意图识别：在机器人的意图识别模块训练，添加说法槽位，见[文档](https://docs.chatopera.com/products/chatbot-platform/howto-guides/intent/intent-maintain.html)。

2）渠道：可以用 Chatopera H5 聊天控件，见机器人的系统集成模块里的 H5 聊天控件，见[文档](https://docs.chatopera.com/products/chatbot-platform/howto-guides/channels/webim-setup.html)。

3）处理用户意图：使用多轮对话设计器，添加意图匹配器，见[文档](https://docs.chatopera.com/products/chatbot-platform/howto-guides/convs/conv-gambit-intent.html)。

参考入门教程的例子：

* https://docs.chatopera.com/products/chatbot-platform/tutorials/index.html

**Comment by kely33** [comment]
这里的闭环是指，用户通过意图识别可以完成订票，在我们票务系统生成一条订单，然后用户可以移步到票务系统完成订单支付，从而实现订票的闭环。
请问这个功能可以实现吗？

**Comment by hailiang-wang** [comment]
可以实现。

1）在多轮对话设计器中，使用意图匹配器，调用你们的业务系统的 API 生成订单。

2）意图匹配器返回订单的支付地址给前端，比如微信小程序，前端跳转到支付页面。

**Comment by kely33** [comment]
ok！
那如果说，我有多重票种供用户购买，那这里的意图识别我该如何精准让客户购买到自己想要的票种？如何设计呢？

**Comment by hailiang-wang** [comment]
在对话检索 API 中，可以携带业务字段：

https://docs.chatopera.com/products/chatbot-platform/references/sdk/chatbot/chat.html?q=extras

<img width="889" alt="screenshot_20230609144912" src="https://github.com/chatopera/docs/assets/3538629/090d4369-9bee-4997-bb21-158685900c95">

多轮对话中，返回自定义字段，给前端识别逻辑。

<img width="587" alt="screenshot_20230609145023" src="https://github.com/chatopera/docs/assets/3538629/0b47839f-36fe-4b4f-83b3-f2003c02b869">

**Comment by hailiang-wang** [comment]
> ok！ 那如果说，我有多重票种供用户购买，那这里的意图识别我该如何精准让客户购买到自己想要的票种？如何设计呢？

在意图识别中，添加一个槽位，该槽位绑定一个自定义词典，比如 productType，在这个词典中，使用：1）词汇表，2）正则表达式。

见词典管理 https://docs.chatopera.com/products/chatbot-platform/howto-guides/dicts/dicts-vocab.html

**Comment by kely33** [comment]
好的，谢谢谢谢

**Comment by hailiang-wang** [comment]
如果您使用春松客服网页渠道，那么处理机器人消息的地方在这里：

在桌面浏览器 - 

https://github.com/cskefu/cskefu/blob/9454a4c9fd46f8d165f60f5d4f29f705dab66d40/contact-center/app/src/main/resources/templates/apps/im/chatbot/index.pug#L680

<img width="631" alt="screenshot_20230609145402" src="https://github.com/chatopera/docs/assets/3538629/67ca27fc-f6ce-40a3-b66e-9e58e623662c">

在移动客户端，H5 -

https://github.com/cskefu/cskefu/blob/9454a4c9fd46f8d165f60f5d4f29f705dab66d40/contact-center/app/src/main/resources/templates/apps/im/chatbot/mobile.pug#L486

从服务端往浏览器发送机器人的消息  -

https://github.com/cskefu/cskefu/blob/9454a4c9fd46f8d165f60f5d4f29f705dab66d40/contact-center/app/src/main/java/com/cskefu/cc/plugins/chatbot/ChatbotEventSubscription.java#L103

**Comment by kely33** [comment]
好的，辛苦帮忙答疑！！

**Comment by hailiang-wang** [comment]
实现逻辑的数据流关系：

访客 <-> 春松客服前端 <-> 春松客服后端 <-> Chatopera 云服务

如果要完成上述的闭环，主要的修改地方是：

1）春松客服前端 JavaScript；2） Chatopera 云服务的意图识别，多轮对话设计器

春松客服后端可能需要修改，它主要是做数据传递的，如果数据没有正常的传递，就需要检查是不是春松客服后端没有转发。
