### ISSUE TITLE
如果两条问题里面部分关键字相同，如何处理呢 。不能同时显示出来吗

### ISSUE THREAD

**Issue by kely33** [chatopera/docs#94]
![0d92111586533af246e692c55f3014c](https://github.com/chatopera/docs/assets/134681303/19219e70-6432-4e8b-8550-ac9e59e92104)
![6dd703c2330ac8a63331a525fdd9e1a](https://github.com/chatopera/docs/assets/134681303/12424fbe-739b-4dae-baf5-81505554820b)
![1686883174605](https://github.com/chatopera/docs/assets/134681303/4133af76-d63e-4bfb-a848-4aed2eebc29f)
目前只显示第一个添加的

**Comment by hailiang-wang** [comment]
不同的问答对代表不同的问题。默认逻辑：最佳回复只有一个。

## 调整

针对您的应用场景，您可以在春松客服中，调整机器人的网页端交互：展示多个问题或答案。

具体的这样做：


1）识别机器人问答接口返回值：

[检索多轮对话](https://docs.chatopera.com/products/chatbot-platform/references/sdk/chatbot/chat.html)接口，返回值的 faq 数组。

<img width="443" alt="screenshot_20230616110139" src="https://github.com/chatopera/docs/assets/3538629/e0b48145-46e1-4cb3-a37c-915fc03dc699">

2）在春松客服中，展示

[后端类处理](https://github.com/cskefu/cskefu/blob/ef69cc328bf84c1ba75745a8e9e93fb8cdfce141/contact-center/app/src/main/java/com/cskefu/cc/plugins/chatbot/ChatbotEventSubscription.java#L237)，[前端展示处理](https://github.com/cskefu/cskefu/blob/ef69cc328bf84c1ba75745a8e9e93fb8cdfce141/contact-center/app/src/main/resources/templates/apps/im/chatbot/index.pug#L681)

**Comment by hailiang-wang** [comment]
对话接口 faq 返回了知识库的检索结果。

**Comment by kely33** [comment]
<img width="646" alt="企业微信截图_16869046281925" src="https://github.com/chatopera/docs/assets/134681303/75367eb3-46fb-45d1-ac99-0a6bc6a84de4">
这里返回值的 faq 数组是空，那您说的展示多个是从哪里拿到多个数据，需要设置什么参数吗？然后才能使数组返回不是空？

**Comment by hailiang-wang** [comment]
>  这里返回值的 faq 数组是空，那您说的展示多个是从哪里拿到多个数据，需要设置什么参数吗？然后才能使数组返回不是空？

这里的返回结果为空，在您的知识库中是有数据的，这里为空代表产品 BUG。
预计下周二可以更新，会在这里给您通知。
感谢您的反馈。

**Comment by hailiang-wang** [comment]
@kely33 
现在该接口: 多轮对话检索。
除该问答被意图匹配器命中外，都有 faq 数据，faq 最多返回 20 个知识库问答对，按照 score 相似度排名，并且为了方便您展示，每个问答对包含了答案的信息。
意图匹配器用来完成意图识别，见，https://docs.chatopera.com/products/chatbot-platform/howto-guides/convs/conv-gambit-intent.html

对于多轮对话检索的知识库返回和模糊匹配器、通配符匹配器，都是可以得到 faq array 信息的。

**Comment by hailiang-wang** [comment]
faq中，每个数组元素看起来是这样的。

![screenshot_20230618165547](https://github.com/chatopera/docs/assets/3538629/a0681d4c-1f58-4991-a1c1-c80757aef2ca)

replies 为答案信息。

**Comment by kely33** [comment]
好的，谢谢谢谢
