### ISSUE TITLE
知识库答案换行问题——设置答案时，进行换行操作，但是机器人回答的内容里并没有换行

### ISSUE THREAD

**Issue by kely33** [chatopera/docs#97]
![image](https://github.com/chatopera/docs/assets/134681303/6c71436a-15c8-465b-b873-83c32e82eda2)
![image](https://github.com/chatopera/docs/assets/134681303/afa74623-b9e0-431b-a922-ba86bdf4ff6d)

**Comment by hailiang-wang** [comment]
使用 https://github.com/cskefu/cskefu/issues/887 追踪。
