### ISSUE TITLE
知识库问答对展示不受设置的最佳阈值与建议回复阈值的影响

### ISSUE THREAD

**Issue by kely33** [chatopera/docs#99]
在chatopera后台知识库问答测试中，“请问出险无忧赔款是什么时候可以支付”该问题得到的阈值是0.84，后台设置的最佳回复阈值则是0.8，但是机器人并没有将该问题的答案直接发送给用户，而是通过建议回复的方式发送给用户
![image](https://github.com/chatopera/docs/assets/134681303/96569a5e-fd93-4860-849c-c8049f723d2d)
![image](https://github.com/chatopera/docs/assets/134681303/32453205-530d-4abb-86ef-f65ec1f7700e)
![image](https://github.com/chatopera/docs/assets/134681303/5c5adf28-1fa8-4a9e-b5f1-bd68df31a992)

**Comment by hailiang-wang** [comment]
在春松客服环境变量上设置了阈值吗？春松客服环境变量的阈值优先级更高。

https://cskefu.gitee.io/cskefu-docs/docs/work-chatbot/install

```
BOT_PROVIDER                 # Chatopera 机器人平台地址，支持私有部署，默认为 Chatopera 云服务 https://bot.chatopera.com
BOT_THRESHOLD_FAQ_BEST_REPLY # 最佳回复阀值
BOT_THRESHOLD_FAQ_SUGG_REPLY # 建议回复阀值
```


从环境变量设置，相当于在请求时，从 RestAPI 中传递，而控制台设置的是默认值，当 API 中没有值时使用默认值。


API - https://docs.chatopera.com/products/chatbot-platform/references/sdk/chatbot/chat.html

![screenshot_20230727144324](https://github.com/chatopera/docs/assets/3538629/2fb3c977-39a3-40b3-8243-6f5432e60aa8)
